image: node:latest

stages:
  - build
  - lint

cache:
  paths:
  - node_modules/

install_dependencies:
  stage: build
  script:
    - cd MaharaMobile
    - npm ci
  artifacts:
    paths:
    - node_modules/

lint:
  stage: lint
  script:
    - cd MaharaMobile
    - npm ci
    - npm run lint
