image: node:18 # :version if needed

stages:
  - build
  - lint
  - test

cache:
  paths:
  - MaharaMobile/node_modules/

install_dependencies:
  stage: build
  script:
    - cd MaharaMobile
    - npm ci --legacy-peer-deps

  artifacts:
    paths:
    - MaharaMobile/node_modules/
    expire_in: 1 day
    when: on_success

lint:
  stage: lint
  script:
    - cd MaharaMobile
    - npm run lint
prettier:
  stage: lint
  script:
    - cd MaharaMobile
    - npm run prettier

test:
  stage: test
  allow_failure: true
  script:
    - cd MaharaMobile
    - npm run extract
    # - npm run test