image: node:latest

stages:
  - build
  - lint
  - test

cache:
  paths:
  - node_modules/

install_dependencies:
  stage: build
  script:
    - cd MaharaMobile
    - npm ci
  artifacts:
    paths:
    - node_modules/

lint:
  stage: lint
  script: "npm run lint"

tests:
  stage: test
  script: "npm run test"
