require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'
permissions_path = '../node_modules/react-native-permissions/ios'
target 'MaharaMobile' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"

  target 'MaharaMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MaharaMobile-tvOS' do
  # Pods for MaharaMobile-tvOS

  target 'MaharaMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
 
